services:
  n8n:
    image: tilt.localhost/n8n:dev
    environment:
      N8N_CUSTOM_EXTENSIONS: /n8n/nodes
      N8N_DEV_RELOAD: 'true'
      N8N_DIAGNOSTICS_ENABLED: 'false'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      N8N_LOG_LEVEL: debug
      N8N_REINSTALL_MISSING_PACKAGES: 'true'
    ports:
      - 5678:5678
    volumes:
      - n8n_persistent:/home/node/.n8n

  paperless-redis:
    image: docker.io/library/redis:7
    restart: unless-stopped

  paperless:
    image: docker.io/paperlessngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-redis
    ports:
      - 8000:8000
    volumes:
      - paperless_data:/usr/src/paperless/data
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
volumes:
  n8n_persistent:
  paperless_data:
